fault_severity = {
    # 🔧 Critical Components
    "engine": True,
    "fuel": True,
    "battery": True,
    "electronics": True,
    "transmission": True,
    "oil": True,
    "wheels": True,
    "brakes": True,
    "lights": True,
    # 🚗 Non-Essential but Useful Components
    "air_conditioning": False,
    "radio": False,
    "gps": False,
    "heated_seats": False,
    "power_windows": False,
    "rear_camera": False,
    "sunroof": False,
    "windshield_wipers": False,
    "horn": False,
    "bluetooth": False,
}


cars_parts = {
    "0001": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": False,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": False,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": False,
        "bluetooth": False,
    },
    "0002": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": False,
        "gps": False,
        "heated_seats": True,
        "power_windows": True,
        "rear_camera": False,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": True,
        "bluetooth": True,
    },
    "0003": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": False,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": False,
        "bluetooth": True,
    },
    "0004": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": True,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": True,
        "bluetooth": True,
    },
    "0005": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": True,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": True,
        "bluetooth": False,
    },
    "0006": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": False,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": True,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": False,
        "windshield_wipers": True,
        "horn": True,
        "bluetooth": True,
    },
    "0007": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": True,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": True,
        "bluetooth": True,
    },
    "0008": {
        # 🔧 Critical Components
        "engine": True,
        "fuel": True,
        "battery": True,
        "electronics": True,
        "transmission": True,
        "oil": True,
        "wheels": True,
        "brakes": True,
        "lights": True,
        # 🚗 Non-Essential but Useful Components
        "air_conditioning": True,
        "radio": True,
        "gps": True,
        "heated_seats": True,
        "power_windows": True,
        "rear_camera": True,
        "sunroof": True,
        "windshield_wipers": True,
        "horn": True,
        "bluetooth": True,
    },
}


car_status_creta = {
    # 🔧 Critical Components
    "engine": True,
    "fuel": True,
    "battery": True,
    "electronics": True,
    "transmission": True,
    "oil": True,
    "wheels": True,
    "brakes": True,
    "lights": True,
    # 🚗 Non-Essential but Useful Components
    "air_conditioning": True,
    "radio": True,
    "gps": True,
    "heated_seats": True,
    "power_windows": True,
    "rear_camera": True,
    "sunroof": True,
    "windshield_wipers": True,
    "horn": True,
    "bluetooth": True,
}

car_status_sportage = {
    # 🔧 Critical Components
    "engine": True,
    "fuel": True,
    "battery": True,
    "electronics": True,
    "transmission": True,
    "oil": True,
    "wheels": True,
    "brakes": True,
    "lights": True,
    # 🚗 Non-Essential but Useful Components
    "air_conditioning": True,
    "radio": True,
    "gps": True,
    "heated_seats": True,
    "power_windows": True,
    "rear_camera": True,
    "sunroof": True,
    "windshield_wipers": True,
    "horn": True,
    "bluetooth": True,
}
